# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoitem', '0002_auto_20171129_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
